.PHONY: clean All

All:
	@echo "----------Building project:[ temp - Debug ]----------"
	@cd "C:\projects\mtech-lab\Computer Networks\temp" && "$(MAKE)" -f  "temp.mk"
clean:
	@echo "----------Cleaning project:[ temp - Debug ]----------"
	@cd "C:\projects\mtech-lab\Computer Networks\temp" && "$(MAKE)" -f  "temp.mk" clean
